### ISSUE TITLE
database telemedicine_storage schema not in code

### ISSUE THREAD

**Issue by girish2477-zz** [stassribnyi/telemedicine#1]
I came across this project and thought of downloading and running. Noticed required telemedicine_storage is not available. Is it possible to share the script to create it ?

**Comment by stassribnyi** [comment]
I haven't worked with this project since graduation, but I will do my best to try making it running

**Comment by girish2477-zz** [comment]
Hi, any luck in finding schema ?

**Comment by stassribnyi** [comment]
Hi, I've found it and created a README.md for this project with as many details as I remember.

The backup file you can find here https://github.com/stassribnyi/telemedicine#getting-started
